Repository Meemaw/Insight, pull requests merged in 2020-05, with the labels that each got.

#38 Hack docker build for auth api
  backend/auth/api/docker/Dockerfile.jvm
  backend/auth/api/src/main/resources/application.properties
  backend/session/api/docker/Dockerfile.jvm
  backend/session/api/src/test/java/com/meemaw/session/resource/v1/SessionResourceTest.java
  backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/service/AuthApi.java
  backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/service/AuthApiExtension.java
  backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/service/AuthApiTestContainer.java
  backend/shared/testing-utils/src/main/java/com/meemaw/test/testconainers/service/AuthApiTestResource.java
Labels: testing

#42 Reviewdog/action misspell@v1
  .github/workflows/backend.yml
  .github/workflows/misspell.yml
  backend/session/api/docker/Dockerfile.jvm
  package.json
  yarn.lock
Labels: auto-merge

#50 ci: use DOCKER_BUILDKIT=1 in ci
  .github/workflows/backend.yml
  .github/workflows/frontend:app.yml
  .github/workflows/frontend:browser:tracking.yml
  .github/workflows/frontend:try.yml
Labels: ci, docker

#53 docs: arhitecture
  docs/arhitecture.md
  docs/arhitecture.png
Labels: documentation

#112 chore: globstar bash
  .github/workflows/backend:check.yml
  backend/config/checkstyle/merge_reports.sh
  backend/config/pmd/merge_reports.sh
  backend/session/session-api/src/main/java/com/meemaw/session/service/PageService.java
Labels: ci

#118 chore: setup spotbugs
  .github/workflows/backend:check.yml
  backend/auth/auth-api/src/main/java/com/meemaw/auth/sso/datasource/HazelcastProvider.java
  backend/build.gradle
  backend/config/spotbugs/merge_reports.py
  backend/settings.gradle
Labels: ci
